[project]
name = "llamastack-impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eder Ignatowicz", email = "ignatowicz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "common",
    "openai>=2.14.0",
    "pydantic>=2.12.5",
]

[project.scripts]
llamastack-impl = "llamastack_impl:main"
llamastack-prompt-chaining = "llamastack_impl.patterns.prompt_chaining.run:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
common = { workspace = true }
